/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LessonCompleteRouteImport } from './routes/lesson-complete'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as HomeHomeRouteImport } from './routes/_home/home'
import { Route as HomeProfileRouteImport } from './routes/_home/profile'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUnitSlugRouteImport } from './routes/admin.$unitSlug'
import { Route as AdminLayarRouteImport } from './routes/admin.layar'
import { Route as AdminPelajaranRouteImport } from './routes/admin.pelajaran'
import { Route as AdminPenggunaRouteImport } from './routes/admin.pengguna'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as HomeUnitsUnitIdRouteImport } from './routes/_home/units.$unitId'
import { Route as AdminUnitSlugIndexRouteImport } from './routes/admin.$unitSlug.index'
import { Route as AdminUnitSlugLessonSlugRouteImport } from './routes/admin.$unitSlug.$lessonSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonCompleteRoute = LessonCompleteRouteImport.update({
  id: '/lesson-complete',
  path: '/lesson-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRoute,
} as any)
const HomeHomeRoute = HomeHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => HomeRoute,
} as any)
const HomeProfileRoute = HomeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnitSlugRoute = AdminUnitSlugRouteImport.update({
  id: '/$unitSlug',
  path: '/$unitSlug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayarRoute = AdminLayarRouteImport.update({
  id: '/layar',
  path: '/layar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPelajaranRoute = AdminPelajaranRouteImport.update({
  id: '/pelajaran',
  path: '/pelajaran',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaRoute = AdminPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AdminRoute,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const HomeUnitsUnitIdRoute = HomeUnitsUnitIdRouteImport.update({
  id: '/units/$unitId',
  path: '/units/$unitId',
  getParentRoute: () => HomeRoute,
} as any)
const AdminUnitSlugIndexRoute = AdminUnitSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUnitSlugRoute,
} as any)
const AdminUnitSlugLessonSlugRoute = AdminUnitSlugLessonSlugRouteImport.update({
  id: '/$lessonSlug',
  path: '/$lessonSlug',
  getParentRoute: () => AdminUnitSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/lesson-complete': typeof LessonCompleteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/about': typeof HomeAboutRoute
  '/home': typeof HomeHomeRoute
  '/profile': typeof HomeProfileRoute
  '/admin/$unitSlug': typeof AdminUnitSlugRouteWithChildren
  '/admin/layar': typeof AdminLayarRoute
  '/admin/pelajaran': typeof AdminPelajaranRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/admin/': typeof AdminIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/units/$unitId': typeof HomeUnitsUnitIdRoute
  '/admin/$unitSlug/$lessonSlug': typeof AdminUnitSlugLessonSlugRoute
  '/admin/$unitSlug/': typeof AdminUnitSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lesson-complete': typeof LessonCompleteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/about': typeof HomeAboutRoute
  '/home': typeof HomeHomeRoute
  '/profile': typeof HomeProfileRoute
  '/admin/layar': typeof AdminLayarRoute
  '/admin/pelajaran': typeof AdminPelajaranRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/admin': typeof AdminIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/units/$unitId': typeof HomeUnitsUnitIdRoute
  '/admin/$unitSlug/$lessonSlug': typeof AdminUnitSlugLessonSlugRoute
  '/admin/$unitSlug': typeof AdminUnitSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_home': typeof HomeRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/lesson-complete': typeof LessonCompleteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_home/about': typeof HomeAboutRoute
  '/_home/home': typeof HomeHomeRoute
  '/_home/profile': typeof HomeProfileRoute
  '/admin/$unitSlug': typeof AdminUnitSlugRouteWithChildren
  '/admin/layar': typeof AdminLayarRoute
  '/admin/pelajaran': typeof AdminPelajaranRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/admin/': typeof AdminIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_home/units/$unitId': typeof HomeUnitsUnitIdRoute
  '/admin/$unitSlug/$lessonSlug': typeof AdminUnitSlugLessonSlugRoute
  '/admin/$unitSlug/': typeof AdminUnitSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/lesson-complete'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/about'
    | '/home'
    | '/profile'
    | '/admin/$unitSlug'
    | '/admin/layar'
    | '/admin/pelajaran'
    | '/admin/pengguna'
    | '/lesson/$lessonId'
    | '/onboarding/welcome'
    | '/admin/'
    | '/onboarding/'
    | '/units/$unitId'
    | '/admin/$unitSlug/$lessonSlug'
    | '/admin/$unitSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/lesson-complete'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/about'
    | '/home'
    | '/profile'
    | '/admin/layar'
    | '/admin/pelajaran'
    | '/admin/pengguna'
    | '/lesson/$lessonId'
    | '/onboarding/welcome'
    | '/admin'
    | '/onboarding'
    | '/units/$unitId'
    | '/admin/$unitSlug/$lessonSlug'
    | '/admin/$unitSlug'
  id:
    | '__root__'
    | '/'
    | '/_home'
    | '/admin'
    | '/forgot-password'
    | '/lesson-complete'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/_home/about'
    | '/_home/home'
    | '/_home/profile'
    | '/admin/$unitSlug'
    | '/admin/layar'
    | '/admin/pelajaran'
    | '/admin/pengguna'
    | '/lesson/$lessonId'
    | '/onboarding/welcome'
    | '/admin/'
    | '/onboarding/'
    | '/_home/units/$unitId'
    | '/admin/$unitSlug/$lessonSlug'
    | '/admin/$unitSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LessonCompleteRoute: typeof LessonCompleteRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-complete': {
      id: '/lesson-complete'
      path: '/lesson-complete'
      fullPath: '/lesson-complete'
      preLoaderRoute: typeof LessonCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/home': {
      id: '/_home/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeHomeRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/profile': {
      id: '/_home/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof HomeProfileRouteImport
      parentRoute: typeof HomeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$unitSlug': {
      id: '/admin/$unitSlug'
      path: '/$unitSlug'
      fullPath: '/admin/$unitSlug'
      preLoaderRoute: typeof AdminUnitSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/layar': {
      id: '/admin/layar'
      path: '/layar'
      fullPath: '/admin/layar'
      preLoaderRoute: typeof AdminLayarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pelajaran': {
      id: '/admin/pelajaran'
      path: '/pelajaran'
      fullPath: '/admin/pelajaran'
      preLoaderRoute: typeof AdminPelajaranRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna': {
      id: '/admin/pengguna'
      path: '/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AdminPenggunaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_home/units/$unitId': {
      id: '/_home/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof HomeUnitsUnitIdRouteImport
      parentRoute: typeof HomeRoute
    }
    '/admin/$unitSlug/': {
      id: '/admin/$unitSlug/'
      path: '/'
      fullPath: '/admin/$unitSlug/'
      preLoaderRoute: typeof AdminUnitSlugIndexRouteImport
      parentRoute: typeof AdminUnitSlugRoute
    }
    '/admin/$unitSlug/$lessonSlug': {
      id: '/admin/$unitSlug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/admin/$unitSlug/$lessonSlug'
      preLoaderRoute: typeof AdminUnitSlugLessonSlugRouteImport
      parentRoute: typeof AdminUnitSlugRoute
    }
  }
}

interface HomeRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeHomeRoute: typeof HomeHomeRoute
  HomeProfileRoute: typeof HomeProfileRoute
  HomeUnitsUnitIdRoute: typeof HomeUnitsUnitIdRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeHomeRoute: HomeHomeRoute,
  HomeProfileRoute: HomeProfileRoute,
  HomeUnitsUnitIdRoute: HomeUnitsUnitIdRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface AdminUnitSlugRouteChildren {
  AdminUnitSlugLessonSlugRoute: typeof AdminUnitSlugLessonSlugRoute
  AdminUnitSlugIndexRoute: typeof AdminUnitSlugIndexRoute
}

const AdminUnitSlugRouteChildren: AdminUnitSlugRouteChildren = {
  AdminUnitSlugLessonSlugRoute: AdminUnitSlugLessonSlugRoute,
  AdminUnitSlugIndexRoute: AdminUnitSlugIndexRoute,
}

const AdminUnitSlugRouteWithChildren = AdminUnitSlugRoute._addFileChildren(
  AdminUnitSlugRouteChildren,
)

interface AdminRouteChildren {
  AdminUnitSlugRoute: typeof AdminUnitSlugRouteWithChildren
  AdminLayarRoute: typeof AdminLayarRoute
  AdminPelajaranRoute: typeof AdminPelajaranRoute
  AdminPenggunaRoute: typeof AdminPenggunaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUnitSlugRoute: AdminUnitSlugRouteWithChildren,
  AdminLayarRoute: AdminLayarRoute,
  AdminPelajaranRoute: AdminPelajaranRoute,
  AdminPenggunaRoute: AdminPenggunaRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OnboardingRouteChildren {
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LessonCompleteRoute: LessonCompleteRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
