/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LessonCompleteRouteImport } from './routes/lesson-complete'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as HomeHomeRouteImport } from './routes/_home/home'
import { Route as HomeProfileRouteImport } from './routes/_home/profile'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUnitIdRouteImport } from './routes/admin.$unitId'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as HomeUnitsUnitIdRouteImport } from './routes/_home/units.$unitId'
import { Route as AdminUnitIdIndexRouteImport } from './routes/admin.$unitId.index'
import { Route as AdminUnitIdLessonIdRouteImport } from './routes/admin.$unitId.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonCompleteRoute = LessonCompleteRouteImport.update({
  id: '/lesson-complete',
  path: '/lesson-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRoute,
} as any)
const HomeHomeRoute = HomeHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => HomeRoute,
} as any)
const HomeProfileRoute = HomeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnitIdRoute = AdminUnitIdRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => AdminRoute,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeUnitsUnitIdRoute = HomeUnitsUnitIdRouteImport.update({
  id: '/units/$unitId',
  path: '/units/$unitId',
  getParentRoute: () => HomeRoute,
} as any)
const AdminUnitIdIndexRoute = AdminUnitIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUnitIdRoute,
} as any)
const AdminUnitIdLessonIdRoute = AdminUnitIdLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => AdminUnitIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/lesson-complete': typeof LessonCompleteRoute
  '/about': typeof HomeAboutRoute
  '/home': typeof HomeHomeRoute
  '/profile': typeof HomeProfileRoute
  '/admin/$unitId': typeof AdminUnitIdRouteWithChildren
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/admin/': typeof AdminIndexRoute
  '/units/$unitId': typeof HomeUnitsUnitIdRoute
  '/admin/$unitId/$lessonId': typeof AdminUnitIdLessonIdRoute
  '/admin/$unitId/': typeof AdminUnitIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lesson-complete': typeof LessonCompleteRoute
  '/about': typeof HomeAboutRoute
  '/home': typeof HomeHomeRoute
  '/profile': typeof HomeProfileRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/admin': typeof AdminIndexRoute
  '/units/$unitId': typeof HomeUnitsUnitIdRoute
  '/admin/$unitId/$lessonId': typeof AdminUnitIdLessonIdRoute
  '/admin/$unitId': typeof AdminUnitIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_home': typeof HomeRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/lesson-complete': typeof LessonCompleteRoute
  '/_home/about': typeof HomeAboutRoute
  '/_home/home': typeof HomeHomeRoute
  '/_home/profile': typeof HomeProfileRoute
  '/admin/$unitId': typeof AdminUnitIdRouteWithChildren
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/admin/': typeof AdminIndexRoute
  '/_home/units/$unitId': typeof HomeUnitsUnitIdRoute
  '/admin/$unitId/$lessonId': typeof AdminUnitIdLessonIdRoute
  '/admin/$unitId/': typeof AdminUnitIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/lesson-complete'
    | '/about'
    | '/home'
    | '/profile'
    | '/admin/$unitId'
    | '/lesson/$lessonId'
    | '/admin/'
    | '/units/$unitId'
    | '/admin/$unitId/$lessonId'
    | '/admin/$unitId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lesson-complete'
    | '/about'
    | '/home'
    | '/profile'
    | '/lesson/$lessonId'
    | '/admin'
    | '/units/$unitId'
    | '/admin/$unitId/$lessonId'
    | '/admin/$unitId'
  id:
    | '__root__'
    | '/'
    | '/_home'
    | '/admin'
    | '/lesson-complete'
    | '/_home/about'
    | '/_home/home'
    | '/_home/profile'
    | '/admin/$unitId'
    | '/lesson/$lessonId'
    | '/admin/'
    | '/_home/units/$unitId'
    | '/admin/$unitId/$lessonId'
    | '/admin/$unitId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LessonCompleteRoute: typeof LessonCompleteRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-complete': {
      id: '/lesson-complete'
      path: '/lesson-complete'
      fullPath: '/lesson-complete'
      preLoaderRoute: typeof LessonCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/home': {
      id: '/_home/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeHomeRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/profile': {
      id: '/_home/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof HomeProfileRouteImport
      parentRoute: typeof HomeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$unitId': {
      id: '/admin/$unitId'
      path: '/$unitId'
      fullPath: '/admin/$unitId'
      preLoaderRoute: typeof AdminUnitIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/units/$unitId': {
      id: '/_home/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof HomeUnitsUnitIdRouteImport
      parentRoute: typeof HomeRoute
    }
    '/admin/$unitId/': {
      id: '/admin/$unitId/'
      path: '/'
      fullPath: '/admin/$unitId/'
      preLoaderRoute: typeof AdminUnitIdIndexRouteImport
      parentRoute: typeof AdminUnitIdRoute
    }
    '/admin/$unitId/$lessonId': {
      id: '/admin/$unitId/$lessonId'
      path: '/$lessonId'
      fullPath: '/admin/$unitId/$lessonId'
      preLoaderRoute: typeof AdminUnitIdLessonIdRouteImport
      parentRoute: typeof AdminUnitIdRoute
    }
  }
}

interface HomeRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeHomeRoute: typeof HomeHomeRoute
  HomeProfileRoute: typeof HomeProfileRoute
  HomeUnitsUnitIdRoute: typeof HomeUnitsUnitIdRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeHomeRoute: HomeHomeRoute,
  HomeProfileRoute: HomeProfileRoute,
  HomeUnitsUnitIdRoute: HomeUnitsUnitIdRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface AdminUnitIdRouteChildren {
  AdminUnitIdLessonIdRoute: typeof AdminUnitIdLessonIdRoute
  AdminUnitIdIndexRoute: typeof AdminUnitIdIndexRoute
}

const AdminUnitIdRouteChildren: AdminUnitIdRouteChildren = {
  AdminUnitIdLessonIdRoute: AdminUnitIdLessonIdRoute,
  AdminUnitIdIndexRoute: AdminUnitIdIndexRoute,
}

const AdminUnitIdRouteWithChildren = AdminUnitIdRoute._addFileChildren(
  AdminUnitIdRouteChildren,
)

interface AdminRouteChildren {
  AdminUnitIdRoute: typeof AdminUnitIdRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUnitIdRoute: AdminUnitIdRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LessonCompleteRoute: LessonCompleteRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
