/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as LessonCompleteRouteImport } from './routes/lesson-complete'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as HomeProfileRouteImport } from './routes/_home/profile'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonCompleteRoute = LessonCompleteRouteImport.update({
  id: '/lesson-complete',
  path: '/lesson-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRoute,
} as any)
const HomeProfileRoute = HomeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeRoute,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/lesson-complete': typeof LessonCompleteRoute
  '/about': typeof HomeAboutRoute
  '/profile': typeof HomeProfileRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/lesson-complete': typeof LessonCompleteRoute
  '/about': typeof HomeAboutRoute
  '/profile': typeof HomeProfileRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/lesson-complete': typeof LessonCompleteRoute
  '/_home/about': typeof HomeAboutRoute
  '/_home/profile': typeof HomeProfileRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/_home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/lesson-complete' | '/about' | '/profile' | '/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/lesson-complete' | '/about' | '/profile' | '/lesson/$lessonId' | '/'
  id:
    | '__root__'
    | '/_home'
    | '/lesson-complete'
    | '/_home/about'
    | '/_home/profile'
    | '/lesson/$lessonId'
    | '/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  LessonCompleteRoute: typeof LessonCompleteRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-complete': {
      id: '/lesson-complete'
      path: '/lesson-complete'
      fullPath: '/lesson-complete'
      preLoaderRoute: typeof LessonCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/profile': {
      id: '/_home/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof HomeProfileRouteImport
      parentRoute: typeof HomeRoute
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HomeRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeProfileRoute: typeof HomeProfileRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeProfileRoute: HomeProfileRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  LessonCompleteRoute: LessonCompleteRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
